baseurl = "/"
languageCode = "en-us"
title = "Nix Theme"
theme = "hugo-theme-nix"

[params]
  GithubID = "prabhu-08"
  TwitterID = "@Prabhudev"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Prabhudev Avarasang"
  HeaderUsername = "prabhu"
  HeaderHostname = "dev"
  Email = "prabhudev.ra@gmail.com"
  About = "info_about_you"
  ProfilePicture = "https://pbs.twimg.com/profile_images/485564678039302144/Fjxv6IbQ.png"
  GoogleAnalytics = "your_google_analytics_id"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
